MFVI:
  hexa_rank: 150
  hexa_std: 1
  iterations: 3
  normalize_weight: true
  quad_rank: 150
  quad_std: 1
  tag_dim: 150
  use_hexalinear: false
  use_quadrilinear: false
  use_second_order: false
  use_third_order: false
  window_size: 1
ModelFinetuner:
  distill_mode: true
  optimizer: SGD
  sentence_level_batch: true
anneal_factor: 0.5
ast:
  Corpus: SEMEVAL16-TR:SEMEVAL16-ES:SEMEVAL16-NL:SEMEVAL16-EN:SEMEVAL16-RU
atis:
  Corpus: ATIS-EN:ATIS-TR:ATIS-HI
chunk:
  Corpus: CONLL_03:CONLL_03_GERMAN
embeddings:
  FastCharacterEmbeddings:
    char_cnn: true
    char_embedding_dim: 25
    hidden_size_char: 25
  FastWordEmbeddings-0:
    embeddings: de
    freeze: true
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    distill_crf: false
    distill_exact: true
    dropout: 0.0
    hidden_size: 256
    relearn_embeddings: true
    sentence_loss: true
    temperature: 3.0
    use_crf: true
model_name: word_char_charcnn_0.5anneal_300epoch_32batch_0.1lr_256hidden_de_monolingual_crf_sentloss_distill_exact_3temperature_10patience_fast_sentbatch_relearn_fasttext_freeze_nodev_ner1
ner:
  Corpus: CONLL_03_GERMAN
  professors:
    config/single-de-ner.yaml: CONLL_03_GERMAN
    config/single-en-ner.yaml: CONLL_03
    config/single-es-ner.yaml: CONLL_03_SPANISH
    config/single-nl-ner.yaml: CONLL_03_DUTCH
  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_0.1lr_256hidden_de_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml
    : CONLL_03_GERMAN
target_dir: resources/taggers/
targets: ner
teacher_annealing: true
train:
  learning_rate: 0.1
  max_epochs: 300
  mini_batch_size: 32
  monitor_test: false
  patience: 10
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
trainer: ModelFinetuner
