ModelFinetuner:
  distill_mode: false
  sentence_level_batch: true
anneal_factor: 2
embeddings:
  BertEmbeddings-0:
    bert_model_or_path: bert-base-multilingual-cased
    fine_tune: true
    layers: '-1'
    pooling_operation: mean
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 256
    locked_dropout: 0.0
    relearn_embeddings: true
    sentence_loss: true
    use_cnn: false
    use_crf: false
    use_rnn: false
    word_dropout: 0.1
model_name: multi-bert_10epoch_32batch_0.00005lr_10000lrrate_multilingual_nocrf_fast_relearn_sentbatch_sentloss_finetune_conlllang_nodev_panx_ner9
ner:
  Corpus: PANX-EN:PANX-DE:PANX-NL:PANX-ES
  professors:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_en_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-EN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_eu_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-EU
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_fa_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-FA
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_fr_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-FR
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_he_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-HE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_id_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner7.yaml
    : PANX-ID
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_sl_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-SL
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_ta_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-TA
  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_en_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-EN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_eu_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-EU
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_fa_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-FA
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_fr_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-FR
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_he_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-HE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_id_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner7.yaml
    : PANX-ID
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_sl_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-SL
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_ta_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-TA
np:
  Corpus: CONLL_03:CONLL_03_GERMAN:CONLL_03_VIETNAMESE
  tag_dictionary: resources/taggers/np_tags.pkl
target_dir: resources/taggers/
targets: ner
teacher_annealing: false
train:
  fine_tune_mode: true
  learning_rate: 5.0e-05
  lr_rate: 10000
  max_epochs: 10
  mini_batch_size: 32
  monitor_test: false
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
trainer: ModelFinetuner
