ModelDistiller:
  distill_mode: true
  train_with_professor: false
anneal_factor: 0.5
dep:
  Corpus: PTB_SL
  dev_file: dev.conllu.sl
  teachers: config/dp_as_sl/word_char_500epoch_0.5inter_5000batch_0.002lr_400hidden_ptb_monolingual_2nd_nocrf_fast_freeze_nodev_dependency30.yaml
  test_file: test.conllu.sl
  train_file: train_modified.bllip.50000.conllu.sl
embeddings:
  FastCharacterEmbeddings: null
  WordEmbeddings:
    embeddings: en
interpolation: 0.05
model:
  DependencySequenceTagger:
    distill_posterior: true
    dropout: 0.5
    hidden_size: 800
    new_drop: true
    rnn_layers: 2
    sentence_loss: true
    temperature: 3
    use_crf: false
model_name: ptb-dp_as_srl-anneal0.5-temp3-50000-2-2nd
target_dir: resources/taggers/
targets: dep
teacher_annealing: true
train:
  learning_rate: 0.1
  max_epochs: 300
  mini_batch_size: 2000
  monitor_test: false
  patience: 10
  professor_interpolation: 0.5
  save_final_model: false
  train_with_dev: false
