ModelFinetuner_dp:
  distill_mode: false
  optimizer: SGD
  sentence_level_batch: true
  train_with_professor: false
anneal_factor: 0

embeddings:
  FastCharacterEmbeddings:
    char_cnn: true
    char_embedding_dim: 25
    hidden_size_char: 25
  FastWordEmbeddings:
    additional_empty_embedding: false
    embeddings: es
    freeze: true
interpolation: 1
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    distill_dp: false
    dropout: 0.0
    hidden_size: 256
    relearn_embeddings: true
    sentence_loss: true
    use_crf: false

model_name: wikiann_baseline_es
ner:
  Corpus: CONLL_03_SPANISH
  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    yzh/config/0831ai/conll03_bs3500_lr1e-3_epoch1k1_char_glove_trainwithdev.yaml: CONLL_03_SPANISH
target_dir: saves/baselines
targets: ner
teacher_annealing: true
train:
  learning_rate: 0.1
  max_epochs: 300
  mini_batch_size: 32
  monitor_test: false
  patience: 10
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
trainer: ModelFinetuner_dp
