ModelFinetuner:
  direct_upsample_rate: -1
  distill_mode: false
  down_sample_amount: -1
  ensemble_distill_mode: false
  language_resample: false
  optimizer: Adam
dependency:
  Corpus: UD_Dutch-LassySmall
embeddings:
  FastCharacterEmbeddings:
    char_embedding_dim: 25
    hidden_size_char: 25
  FastWordEmbeddings-0:
    embeddings: nl
    freeze: true
enhancedud:
  Corpus: UD_English-EWT
is_teacher_list: true
is_toy: false
model:
  SemanticDependencyParser:
    binary: false
    dropout: 0.0
    factorize: true
    hidden_size: 400
    init_std: 0.25
    interpolation: 0.5
    iterations: 3
    lstm_dropout: 0.33
    mlp_dropout: 0.33
    n_mlp_arc: 500
    n_mlp_rel: 100
    n_mlp_sec: 150
    rnn_layers: 3
    tree: false
    use_cop: false
    use_crf: false
    use_gp: true
    use_rnn: true
    use_second_order: true
    use_sib: true
    word_dropout: 0.33
model_name: dutch-teacher
srl:
  Corpus: SRL-EN
target_dir: resources/taggers/
targets: dependency
teacher_annealing: false
train:
  betas:
  - 0.9
  - 0.9
  fine_tune_mode: false
  learning_rate: 0.002
  lr_rate: 1
  max_epochs: 500
  min_freq: 2
  mini_batch_size: 5000
  monitor_test: false
  save_final_model: false
  sort_data: true
  train_with_dev: false
  true_reshuffle: false
trainer: ModelFinetuner
