ModelDistiller:
  distill_mode: false
  train_with_professor: false
anneal_factor: 2
embeddings:
#  BertEmbeddings:
#    bert_model_or_path: bert-base-multilingual-cased
#    layers: '-1'
#    pooling_operation: mean
#  FlairEmbeddings-1:
#    model: de-forward
#  FlairEmbeddings-2:
#    model: de-backward
  FastCharacterEmbeddings:
  WordEmbeddings:
    embeddings: en
interpolation: 0.05
#is_teacher_list: true
model:
  DependencySequenceTagger:
    distill_posterior: false
    hidden_size: 800
    rnn_layers: 2
    sentence_loss: true
    use_crf: false
    new_drop: true
    dropout: 0.5
model_name: ptb-dp_as_srl-10000-unteacher1
dep:
  Corpus: PTB_SL
  train_file: train_modified.bllip.60.10000.conllu.sl
  dev_file: dev.conllu.sl
  test_file: test.conllu.sl
#  professors:
#    config/single-de-ner.yaml: CONLL_03_GERMAN
#    config/single-en-ner.yaml: CONLL_03
#    config/single-es-ner.yaml: CONLL_03_SPANISH
#    config/single-nl-ner.yaml: CONLL_03_DUTCH
#  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    config/dp_as_sl/word_char_500epoch_0.5inter_5000batch_0.002lr_400hidden_ptb_monolingual_nocrf_fast_freeze_nodev_dependency30.yaml
#    config_gen/multi_bert_flair_2000batch_1lr_en_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner1.yaml: CONLL_03
#    config_gen/multi_bert_flair_2000batch_1lr_es_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner0.yaml: CONLL_03_SPANISH
#    config_gen/multi_bert_flair_2000batch_1lr_nl_monolingual_nocrf_sentloss_10patience_baseline_nodev_ner1.yaml: CONLL_03_DUTCH
target_dir: resources/taggers/
targets: dep
teacher_annealing: false
train:
  learning_rate: 0.1
  max_epochs: 300
  mini_batch_size: 2000
  monitor_test: false
  patience: 10
  professor_interpolation: 0.5
  save_final_model: false
  train_with_dev: false
#upos:
#  Corpus: UD_GERMAN:UD_ENGLISH:UD_FRENCH:UD_ITALIAN:UD_DUTCH:UD_SPANISH:UD_PORTUGUESE:UD_CHINESE
#  UD_GERMAN:
#    train_config: config/
#  tag_dictionary: resources/taggers/pos_tags.pkl
